global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'flask_app'
    metrics_path: '/metrics'
    dns_sd_configs:
      - names: ['web']
        type: 'A'
        port: 5000

  - job_name: "cadvisor"
    static_configs:
      - targets: ['cadvisor:8080']
