global:
  scrape_interval: 5s # Как часто забирать данные

scrape_configs:
  - job_name: 'flask_app'
    static_configs:
      - targets: ['web:5000']
  - job_name: "cadvisor"
    static_configs:
      - targets: ['cadvisor:8080']