events { worker_connections 1024; }

http {
    upstream web {
	server web:5000;
    }

    server {
	listen 80;
        root /usr/share/nginx/html/static_pages; # Корень, куда мы примонтировали папку
	index page138366646.html; # Какую страницу открывать по умолчанию (просто /)
        
	location / {
	    # Сначала ищем точный файл ($uri), 
            # потом с расширением .html (для красивых ссылок),
            # если нет — идем во Flask
            try_files $uri $uri.html @flask;
        }

	location @flask  {
            resolver 127.0.0.11 valid=5s;
	    set $upstream_app web:5000;
	    proxy_pass http://$upstream_app;

    	    proxy_set_header Host $host;
    	    proxy_set_header X-Real-IP $remote_addr;
    	    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	}
    }
}