[app]
192.168.1.10 static_ip=192.168.1.10 interface_name=enp0s3

[infra]
192.168.1.20 static_ip=192.168.1.20 interface_name=enp0s3

[all:vars]
ansible_user=olga2
ansible_ssh_private_key_file=~/.ssh/id_ed25519
gateway=192.168.1.1
dns_server=8.8.8.8