services:

  db:
    restart: &restart-policy unless-stopped
    image: postgres:latest
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql
    networks:
      - olga2_network

  nginx:
    restart: *restart-policy
    build: ./nginx
    ports:
      - "80:80"
    networks:
      - olga2_network

  load-gen:
    restart: *restart-policy
    build: ./load-gen
    networks:
      - olga2_network
    depends_on:
      - nginx

  prometheus:
    restart: *restart-policy
    image: prom/prometheus:latest
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - olga2_network
    deploy:
      resources:
        limits:
          memory: 256M


  grafana:
    restart: *restart-policy
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/dashboards_provider.yml:/etc/grafana/provisioning/dashboards/provider.yml
      - ./monitoring/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    networks:
      - olga2_network

  homer:
    image: b4bz/homer:latest
    container_name: homer
    volumes:
      - ./homer:/www/assets
    ports:
      - '8080:8081'
    restart: *restart-policy
volumes:
  db_data:

networks:
  olga2_network: {}