name: Deploy to VM
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_FILE_CONTENT }}" > .env

      - name: Deploy Docker Compose
        run: |
          docker compose up -d --build --scale web=5
          docker compose restart prometheus nginx grafana